# Generated by Django 5.1.2 on 2025-06-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
    ]
