# Generated by Django 5.1.2 on 2025-04-25 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="best_seller",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="volume",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainapp.volume",
            ),
        ),
    ]
