# Generated by Django 5.1.2 on 2025-04-25 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_product_best_seller_alter_productvariant_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvariant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
