# Generated by Django 5.1.2 on 2025-04-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_productvariant_created_at_productvariant_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="follow",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="index",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="keywords",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="meta_description",
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="meta_title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
