# Generated by Django 5.1.2 on 2025-04-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_productvariant_follow_productvariant_index_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="volume",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_giftcard",
        ),
        migrations.DeleteModel(
            name="Volume",
        ),
    ]
