# Generated by Django 5.1.2 on 2025-04-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_remove_productvariant_volume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="keywords",
            field=models.TextField(
                blank=True,
                help_text="Enter comma-separated keywords like attar, perfume, fragrance.",
                null=True,
            ),
        ),
    ]
