# Generated by Django 5.1.2 on 2025-04-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_alter_productvariant_keywords"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="SubCategory",
        ),
        migrations.AddField(
            model_name="productcategory",
            name="follow",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="index",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="keywords",
            field=models.TextField(
                blank=True,
                help_text="Enter comma-separated keywords like attar, perfume, fragrance.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="meta_description",
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="meta_title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
