# Generated by Django 5.1.2 on 2025-05-02 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_shiprockettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_company_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_company_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainapp.productvariant",
            ),
        ),
    ]
