# Generated by Django 5.1.2 on 2025-05-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_order_shipping_company_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_company_price",
        ),
    ]
