# Generated by Django 5.1.2 on 2025-05-06 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_remove_order_shipping_company_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="giftcard",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="label",
            field=models.FileField(blank=True, null=True, upload_to="lables"),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_schedule_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_token_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Paid", "Paid"),
                    ("Failed", "Failed"),
                    ("other", "other"),
                ],
                default="Pending",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="ReturnExchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("Return", "Return"), ("Exchange", "Exchange")],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("PENDING", "PENDING"),
                            ("COMPLETED", "COMPLETED"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_note", models.TextField(blank=True)),
                ("awb_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "shiprocket_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("shipment_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "pickup_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "pickup_schedule_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "pickup_token_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "manifest",
                    models.FileField(blank=True, null=True, upload_to="manifests"),
                ),
                ("label", models.FileField(blank=True, null=True, upload_to="labels")),
                (
                    "shiprocket_invoice",
                    models.FileField(
                        blank=True, null=True, upload_to="shiprocket_invoice"
                    ),
                ),
                ("tracking_link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.orderitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Return/Exchange Request",
                "verbose_name_plural": "Return/Exchange Requests",
            },
        ),
        migrations.DeleteModel(
            name="Currency",
        ),
        migrations.DeleteModel(
            name="GiftCard",
        ),
    ]
