# Generated by Django 5.1.2 on 2025-05-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0012_alter_order_options_rename_bredth_product_breadth_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="shipping_company_id",
            new_name="courier_company",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="shipping_company_name",
            new_name="courier_company_id",
        ),
    ]
