# Generated by Django 5.1.2 on 2025-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0013_rename_shipping_company_id_order_courier_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shiprocket_invoice",
            field=models.FileField(
                blank=True, null=True, upload_to="shiprocket_invoice"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_combo",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="label",
            field=models.FileField(blank=True, null=True, upload_to="labels"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "COD"), ("ONLINE", "ONLINE")],
                default="COD",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="recommended",
            field=models.BooleanField(default=False),
        ),
    ]
