# Generated by Django 5.1.2 on 2025-05-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0014_order_shiprocket_invoice_product_is_combo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="alt_tag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
