# Generated by Django 5.1.2 on 2025-05-13 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0016_productseries_product_series"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productseries",
            options={"verbose_name_plural": "Product Series"},
        ),
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(default="INR", max_length=15),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="refund_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refund_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="refund_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("Paid", "Paid"),
                    ("Failed", "Failed"),
                    ("Refunded", "Refunded"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
