# Generated by Django 5.1.2 on 2025-05-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0017_alter_productseries_options_transaction_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="category_icon",
            field=models.ImageField(blank=True, null=True, upload_to="category_icons"),
        ),
    ]
