# Generated by Django 5.1.2 on 2025-05-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0018_productcategory_category_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="productvariant",
            name="notes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="note", to="mainapp.notes"
            ),
        ),
    ]
