# Generated by Django 5.1.2 on 2025-05-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0019_notes_productvariant_notes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notes",
            options={"verbose_name_plural": "Notes"},
        ),
        migrations.AddField(
            model_name="notes",
            name="type",
            field=models.CharField(default="BASE_NOTE", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notes",
            name="description",
            field=models.TextField(
                blank=True,
                choices=[
                    ("TOP_NOTE", "TOP_NOTE"),
                    ("HEART_NOTE", "HEART_NOTE"),
                    ("BASE_NOTE", "BASE_NOTE"),
                ],
                default="TOP_NOTE",
                null=True,
            ),
        ),
    ]
