# Generated by Django 5.1.2 on 2025-05-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0020_alter_notes_options_notes_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notes",
            name="type",
            field=models.CharField(
                choices=[
                    ("TOP_NOTE", "TOP_NOTE"),
                    ("HEART_NOTE", "HEART_NOTE"),
                    ("BASE_NOTE", "BASE_NOTE"),
                ],
                default="TOP_NOTE",
                max_length=100,
            ),
        ),
    ]
