# Generated by Django 5.1.2 on 2025-06-04 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0021_alter_notes_description_alter_notes_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactus",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="contactus",
            name="last_name",
        ),
    ]
